### ISSUE TITLE
COM changes for GFSv17 COM reorganization

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/prepobs#17]
As part of the GFSv17 upgrade the structure of COM is changing. Companion changes are needed in prepobs. See more in the global-workflow issue: https://github.com/NOAA-EMC/global-workflow/issues/761

@ilianagenkova When a prepobs release branch is created for the GFSv17 implementation these changes should be included. Will hold in a feature branch ([feature/GFSv17_com_reorg](https://github.com/NOAA-EMC/prepobs/tree/feature/GFSv17_com_reorg)) until that point for use by GFS developers running cycled experiments. Will keep the feature branch synced with operational updates as needed until release branch for v17 is created.

Changes provided by @WalterKolczynski-NOAA from his COM reorg testing.

**Comment by ilianagenkova** [comment]
All bufr dumps (*.bufr_d) and various flavors of prepbufr files are written in the same directory, so this should be a coordinated GFSv17 - obsproc/prepobs/bufr-dump update.

@WalterKolczynski-NOAA, when you say COM do you mean $COMROOT/gfs/{gfs_ver}/...  ? Just to be clear.
Operationally, observations can't go there, but in $COMROOT/obsproc. 

We can change the path from:
$COMROOT/obsproc/{obsproc_ver}/gdas[gfs].{pdy}/{cc}/atmos/*bufr.d[*prepbufr]
to
$COMROOT/obsproc/{obsproc_ver}/gdas[gfs].{pdy}/{cc}/*bufr.d[*prepbufr]
Is this the ask?

**Comment by WalterKolczynski-NOAA** [comment]
@ilianagenkova This is more about the location of the GFS files moving than anything about the location of obs. For development purposes, we also link in obs from the dump archive and that is also changing, but that shouldn't matter for prepobs/obsproc. I believe the only change will be to `ush/getges_driver.sh`. We'll be making the changes, so I don't think we need anything from you right now.

**Comment by ilianagenkova** [comment]
@WalterKolczynski-NOAA, I got it...it's you impacting us, thanks!  Not long ago there was a separate convo about merging /atmos and /wave observations to just /obs , so I jumped to conclusions.

Yes, let us know where the guess fields end up so we update _getges_. Thank you!

**Comment by KateFriedman-NOAA** [comment]
Completed via PR #19. Closing as complete.
