### ISSUE TITLE
Add Hercules support

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/prepobs#21]
The new MSU partition Hercules has come online. Add support for Hercules.

See https://github.com/NOAA-EMC/global-workflow/issues/1588 for more details.

**Comment by DavidHuber-NOAA** [comment]
Hercules appears to be able to use the Orion installation (after loading the MKL library) just fine and does not need to be ported.  It may be worthwhile to do this port sometime in the future (i.e. at Orion end of life) so it can be installed on Hercules, but is not necessary in the short term.  Additionally, prepobs would need to be ported to Intel 2022 and spack-stack to be buildable on Hercules, so I suggest we skip this for now.

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA Sounds good to me!

**Comment by KateFriedman-NOAA** [comment]
Hercules support was added in PR #23. Closing this as complete.
