### ISSUE TITLE
Setup prepobs dev/gfsv17 to compile and run C96_atm3DVar CI test on Gaea-C5

### ISSUE THREAD

**Issue by DavidBurrows-NCO** [NOAA-EMC/prepobs#32]
Update build files and add Gaea-specific module files to compile and run prepobs branch dev/gfsv17 C96_atm3DVar on Gaea-C5

Ref NOAA-EMC/global-workflow [#2766](https://github.com/NOAA-EMC/global-workflow/issues/2766)

**Comment by DavidBurrows-NCO** [comment]
Hi @KateFriedman-NOAA I am getting ready to submit PRs for cycled runs on Gaea. I have a quick question that will probably lead to a few more questions...I see you updated GFSv17 branch to v1.1.0 in #34.  What branch/tag should I be comparing my prepobs branch to? Thanks!

**Comment by KateFriedman-NOAA** [comment]
@DavidBurrows-NCO Use the [`dev/gfsv17` branch in the authoritative prepobs repo](https://github.com/NOAA-EMC/prepobs/tree/dev/gfsv17). That's our branch with changes to support GFSv17 COM restructure and R&D support. Eventually it will be merged into a release branch for ops, likely closer to GFSv17 hand-off time.

Send a PR with the Gaea changes into it from your fork. I'm happy to be a reviewer on that PR. Let me know if you have any questions about updating prepobs for Gaea.

**Comment by DavidBurrows-NCO** [comment]
Thanks @KateFriedman-NOAA. The dev/gfsv17 branch was hiding. I had to zoom out my web browser to see it. I'm doing one last final test run soon and will submit the group of PRs later this afternoon.

**Comment by KateFriedman-NOAA** [comment]
Have retagged the `prepobs.v1.1.0-rd-gfsv17` tag. Closing as complete.

**Comment by KateFriedman-NOAA** [comment]
@DavidBurrows-NCO You can now install the prepobs `prepobs.v1.1.0-rd-gfsv17` tag on Gaea in a folder called `v1.1.0` and include that in your global-workflow branch in the Gaea module_base.

**Comment by DavidBurrows-NCO** [comment]
@KateFriedman-NOAA I was able to check out the `prepobs.v1.1.0-rd-gfsv17` tag and copied to a `v1.1.0` directory. I am trying to get the package built but it keeps installing to `HOMEprepobs/install`.  Is there a way to get it installed directly at `HOMEprepobs`? Thanks.

**Comment by KateFriedman-NOAA** [comment]
@DavidBurrows-NCO Sorry, should have provided the recommended install command:

```
INSTALL_TARGET=gaea INSTALL_PREFIX=path_to_v1.1.0_folder ./ush/build.sh
```

**Comment by DavidBurrows-NCO** [comment]
@KateFriedman-NOAA Forgot to say thanks, and this worked as expected.

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA Forgot to say thanks, and this worked as expected.

No worries, glad it worked! :)
