### ISSUE TITLE
Port cron to WCOSS2 that generates 48 hours old aircraft dump and prepbufr files that are 100% non-restricted

### ISSUE THREAD

**Issue by ShelleyMelchior-NOAA** [NOAA-EMC/prepobs#4]
Related to https://github.com/NOAA-EMC/obsproc/issues/33

Impacted code in prepobs:
`scripts/exprep_post.sh`

**Comment by ShelleyMelchior-NOAA** [comment]
Squash merged `release/prepobs.v1.0.0` into `feature/48hr-old-aircraft-nr-33` to keep in sync w/ latest code that NCO is running in para on wc2.

**Comment by ShelleyMelchior-NOAA** [comment]
Completed changes to **exprep_post.sh** in `feature/48hr-old-aircraft-nr-33`.

**Comment by ShelleyMelchior-NOAA** [comment]
Was able to build and install on cactus and dogwood: `/lfs/h2/emc/obsproc/noscrub/Shelley.Melchior/install/prepobs-nr-33`

**Comment by ilianagenkova** [comment]
@ShelleyMelchior-NOAA , when you get a chance, please check that  $PACKAGEROOT/obsproc.v1.2.0 has everything from feature/48hr-old-aircraft-nr-33 and we can then close this issue. thanks!

**Comment by ilianagenkova** [comment]
Implemented in obsproc v1.2
